import datetime

def generate_markdown_report(filename, profile, issues, score, ai_analysis):
    """
    Generate a comprehensive markdown report.
    """
    report = f"""# Data Quality Assessment Report: {filename}
Generated on: {datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

## 1. Executive Summary
- **Overall Quality Score:** {score['overall_score']}/100
- **Total Rows:** {profile['row_count']}
- **Total Columns:** {profile['column_count']}
- **Duplicate Rows:** {profile['duplicate_rows']}

## 2. Quality Score Breakdown
| Dimension | Score |
|-----------|-------|
| Completeness | {score['dimensions']['Completeness']}% |
| Uniqueness | {score['dimensions']['Uniqueness']}% |
| Validity & Consistency | {score['dimensions']['Validity & Consistency']}% |

## 3. Detected Issues
| Type | Column | Count | Severity | Description |
|------|--------|-------|----------|-------------|
"""
    
    for issue in issues:
        report += f"| {issue['type']} | {issue['column']} | {issue['count']} | {issue['severity']} | {issue['description']} |\n"

    report += f"""
## 4. AI-Generated Insights & Recommendations
{ai_analysis}

---
*Report generated by DataGuardian AI*
"""
    return report
